@url=http://localhost:3000/api/auth
@authToken= {{login.response.body.$.token}}

### Register User
POST {{ url }}/register
Content-Type: application/json

{
    "name": "Kembert Nieves",
    "email": "knieves@gmail.com",
    "password": "ll1234_55678Añ"
}

### Login User
# @name login
POST {{ url }}/login
Content-Type: application/json

{
    "email": "knieves@gmail.com",
    "password": "ll1234_55678Añ"
}

### Verify user token
GET {{ url }}/verify-token
Content-Type: application/json
Authorization: bearer {{authToken}}

