apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webhooks-service
  name: webhooks-service
spec:
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: webhooks-ms
  type: NodePort
status:
  loadBalancer: {}
