const KEY_MICROSERVICES_SERVICES = {
  PRODUCT: 'PRODUCT_SERVICE',
  ORDER: 'ORDER_SERVICE',
  NATS_SERVICE: 'NATS_SERVICE',
};

const TCP_EVENTS = {
  PRODUCT: {
    CREATE: 'PRODUCT_CREATE',
    FIND_ALL: 'PRODUCT_FIND_ALL',
    FIND_ONE: 'PRODUCT_FIND_ONE',
    UPDATE: 'PRODUCT_UPDATE',
    DELETE: 'PRODUCT_DELETE',
    VALIDATE: 'PRODUCT_VALIDATE',
  },
  ORDER: {
    CREATE: 'ORDER_CREATE',
    FIND_ALL: 'ORDER_FIND_ALL',
    FIND_ONE: 'ORDER_FIND_ONE',
    UPDATE_STATUS: 'ORDER_UPDATE_STATUS',
  },
};

export const CONSTANTS = {
  TCP_EVENTS,
  KEY_MICROSERVICES_SERVICES,
};
