const KEY_MICROSERVICES_SERVICES = {
  PRODUCT: 'PRODUCT_SERVICE',
  ORDER: 'ORDER_SERVICE',
  NATS_SERVICE: 'NATS_SERVICE',
};

const EVENT_MESSAGES = {
  PRODUCT: {
    CREATE: 'PRODUCT.CREATE',
    FIND_ALL: 'PRODUCT.FIND.ALL',
    FIND_ONE: 'PRODUCT.FIND.ONE',
    UPDATE: 'PRODUCT.UPDATE',
    DELETE: 'PRODUCT.DELETE',
    VALIDATE: 'PRODUCT.VALIDATE',
  },
  ORDER: {
    CREATE: 'ORDER.CREATE',
    FIND_ALL: 'ORDER.FIND.ALL',
    FIND_ONE: 'ORDER.FIND.ONE',
    UPDATE_STATUS: 'ORDER.UPDATE.STATUS',
  },
  PAYMENT: {
    SUCCEEDED: 'PAYMENT.SUCCEEDED',
    SESSION: 'PAYMENT.SESSION',
  },
  AUTH: {
    REGISTER: 'AUTH.REGISTER',
    LOGIN: 'AUTH.LOGIN',
    VERIFY_TOKEN: 'AUTH.VERIFY.TOKEN',
  },
};

export const CONSTANTS = {
  EVENT_MESSAGES,
  KEY_MICROSERVICES_SERVICES,
};
