version: '3'
services:
  client-gateway:
    image: client-gateway
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.prod
      labels:
        - 'client-gateway:latest'
      args:
        PROJECT_NAME: client-gateway
    env_file:
      - .env
  auth-ms:
    image: auth-ms
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.prod
      labels:
        - 'auth-ms:latest'
      args:
        PROJECT_NAME: 'auth'
        AUTH_DATABASE: ${AUTH_DATABASE_URL}
    env_file:
      - .env
  products-ms:
    image: products-ms
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.prod
      labels:
        - 'products-ms:latest'
      args:
        PROJECT_NAME: 'products'
        PRODUCTS_DATABASE: ${PRODUCTS_DATABASE_URL}
    env_file:
      - .env
  orders-ms:
    image: orders-ms
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.prod
      labels:
        - 'orders-ms:latest'
      args:
        PROJECT_NAME: 'orders'
        ORDERS_DATABASE: ${ORDERS_DATABASE_URL}
    env_file:
      - .env
  webhooks-ms:
    image: webhooks-ms
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.prod
      labels:
        - 'webhooks-ms:latest'
      args:
        PROJECT_NAME: 'webhooks'
    env_file:
      - .env
