version: '3'
services:
  client-gateway:
    image: client-gateway
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.prod
      labels:
        - 'client-gateway:latest'
      args:
        PROJECT_NAME: client-gateway
    env_file:
      # - ../apps/client-gateway/.env
      - .env
  # auth:
  #   image: us-east4-docker.pkg.dev/payment-microservices/image-registry/auth
  #   build:
  #     context: ../
  #     dockerfile: ./dockerfiles/Dockerfile.prod
  #     args:
  #       PROJECT_NAME: 'auth'
  #   env_file:
  #     # - ../apps/auth/.env
  #     - ../.env
  products-ms:
    image: products-ms
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.prod
      labels:
        - 'products-ms:latest'
      args:
        PROJECT_NAME: 'products'
        PRODUCTS_DATABASE: ${PRODUCTS_DATABASE_URL}
    env_file:
      # - ../apps/products/.env
      - .env
  # orders:
  #   image: us-east4-docker.pkg.dev/payment-microservices/image-registry/orders
  #   build:
  #     context: ../
  #     dockerfile: ./dockerfiles/Dockerfile.prod
  #     args:
  #       PROJECT_NAME: orders
  #       ORDERS_DATABASE: ${ORDERS_DATABASE_URL}
  #   env_file:
  #     # - ../apps/orders/.env
  #     - ../.env
  # webhooks:
  #   image: us-east4-docker.pkg.dev/payment-microservices/image-registry/webhook
  #   build:
  #     context: ../
  #     dockerfile: ./dockerfiles/Dockerfile.prod
  #     args:
  #       PROJECT_NAME: 'webhooks'
  #   env_file:
  #     # - ../apps/webhooks/.env
  #     - ../.env
