name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      # Instal dependencies
      - run: npm ci --legacy-peer-deps

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > dockerfiles/.env

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Docker Build, Tag And Push to Artifact Registry
        run: |
          docker-compose -f dockerfiles/docker-compose.prod.yml build
          services=$(docker-compose -f dockerfiles/docker-compose.prod.yml config --services)
          for service in $services; do
            docker tag $service us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/image-registry/$service:latest
            docker push us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/image-registry/$service:latest
          done
